// Generated by sync-graph-to-github.py @ 2026-05-13 02:03
// 5主题Tab视图 + 资讯tag双轨分类
const KNOWLEDGE_DATA = {
  nodes: [
    { id: "td-6", label: "重要发言（刘烈宏）", theme: "可信数据空间", tag_category: "数据基础设施", topics: "可信数据空间", source: "/tmp/ndrc-trustworthy-data-space-20260429.md", url: "", date: "2026-04-29", summary: "**核心观点：** 1. 可信数据空间的定位： - 不仅是一种数据基础设施 - 更是数据共享共治、价值协作的产业生态 - 是推进全国一体化数据市场建设、推动数据要素市场化价值化的重要抓手 2. 对三类主体的要求： - **数据管理部门**：加强政策宣贯落实，将数据空间作为促进数据开发利用、培育数据产业、构建数据要素市场体系的关键抓手 - **产业联盟**：强化专业化服务能力，做好服务、凝聚生态，引", quality: 73.5, connections: 0, success_rate: null },
    { id: "vp-1", label: "与朗新的关联", theme: "虚拟电厂", tag_category: "数据基础设施", topics: "虚拟电厂,充电桩,可信数据空间,朗新科技", source: "/tmp/ndrc-trustworthy-data-space-20260429.md", url: "", date: "2026-04-29", summary: "1. **可信数据空间**：朗新科技在能源电力领域有数据流通实践，与可信数据空间战略高度相关 2. **北数所互联互通项目**：已与北数所开展Open API对接，可参与可信数据空间生态 3. **能源数据空间**：充电桩/储能/虚拟电厂数据流通 = 能源可信数据空间的具体场景 4. **参考标准**：联盟成立后将推进标准研制，朗新可关注能源电力数据空间标准", quality: 63.5, connections: 0, success_rate: null },
    { id: "td-2", label: "北京市政数局:北数所已聚拢数据生态企业超1000家", theme: "可信数据空间", tag_category: "市场", topics: "可信数据空间", source: "data-market-insight", url: "https://cdn.jsdelivr.net/gh/Domi-OpenClaw/file-storage@main/知识管理/km_2f22bc383eb7_%E5%8C%97%E4%BA%AC%E5%B8%82%E6%94%BF%E6%95%B0%E5%B1%80%3A%E5%8C%97%E6%95%B0%E6%89%80%E5%B7%B2%E8%81%9A%E6%8B%A2%E6%95%B0%E6%8D%AE%E7%94%9F%E6%80%81%E4%BC%81%E4%B8%9A%E8%B6%85.md", date: "2026-04-17", summary: "2025年,北京市委市政府出台《关于建设数据要素综合试验区 深化数据要素市场化配置改革的实施意见》,明确试验区“243”建设框架,实现从顶层设计到全面建设的良好开局。 具体来看,一方面,北京夯实数据要素基础环境,创新数据产权制度落地路径,出台公共数据资源开发利用、登记管理实施细则等一批数据制度,加快推进北京数据条例立法。鼓励市场主体围绕新材料、消费、药品、空天等领域建设一批可信数据空间,14个在京", quality: 79.5, connections: 0, success_rate: null },
    { id: "td-3", label: "深圳数交所助推国内首个智能制造数据空间应用案例落地-深圳政府在线_深圳市人民政府门户网站", theme: "可信数据空间", tag_category: "市场", topics: "可信数据空间", source: "data-market-insight", url: "https://cdn.jsdelivr.net/gh/Domi-OpenClaw/file-storage@main/知识管理/km_f76e8e51877f_%E6%B7%B1%E5%9C%B3%E6%95%B0%E4%BA%A4%E6%89%80%E5%8A%A9%E6%8E%A8%E5%9B%BD%E5%86%85%E9%A6%96%E4%B8%AA%E6%99%BA%E8%83%BD%E5%88%B6%E9%80%A0%E6%95%B0%E6%8D%AE%E7%A9%BA%E9%97%B4%E5%BA%94.md", date: "2026-04-17", summary: "近日,深圳交易集团有限公司(深圳公共资源交易中心)(以下简称“深交易”)旗下深圳数据交易所(以下简称“深圳数交所”)携手四川长虹电子控股集团有限公司(以下简称“长虹控股”)､深圳数鑫科技有限公司(以下简称“数鑫科技”)､中国信息通信研究院(以下简称“信通院”)完成了国内首笔基于数据空间技术的场内数据业务合作,打造出我国首个智能制造领域数据空间应用案例｡这标志着可信数据空间技术正式实现国产商业化落地", quality: 61.5, connections: 0, success_rate: null },
    { id: "td-4", label: "广东:建设公共数据运营平台 鼓励各地结合实际开展公共数据授权运营", theme: "可信数据空间", tag_category: "市场", topics: "可信数据空间", source: "data-market-insight", url: "https://cdn.jsdelivr.net/gh/Domi-OpenClaw/file-storage@main/知识管理/km_62c2e4b06cf5_%E5%B9%BF%E4%B8%9C%3A%E5%BB%BA%E8%AE%BE%E5%85%AC%E5%85%B1%E6%95%B0%E6%8D%AE%E8%BF%90%E8%90%A5%E5%B9%B3%E5%8F%B0%20%E9%BC%93%E5%8A%B1%E5%90%84%E5%9C%B0%E7%BB%93%E5%90%88.md", date: "2026-04-17", summary: "广东省发展改革委印发《广东省2026年优化市场化一流营商环境工作方案》,其中指出,释放数据要素活力｡建立公共数据共享开放需求受理反馈机制,动态优化“开放广东”平台数据开放目录,推进企业登记､交通､地理､卫星遥感､气象､教育､医疗卫生等高价值数据集依法依规分类开放｡建设公共数据运营平台,鼓励各地结合实际开展公共数据授权运营｡完善法人数字空间功能,建设“一企一档”,支持企业建设企业可信数据空间,推进数", quality: 69.0, connections: 0, success_rate: null },
    { id: "td-5", label: "董学耕公共数据授权运营实现路径全解析", theme: "可信数据空间", tag_category: "政策", topics: "可信数据空间", source: "data-market-insight", url: "https://cdn.jsdelivr.net/gh/Domi-OpenClaw/file-storage@main/知识管理/km_37653bc094cf_%E8%91%A3%E5%AD%A6%E8%80%95%E5%85%AC%E5%85%B1%E6%95%B0%E6%8D%AE%E6%8E%88%E6%9D%83%E8%BF%90%E8%90%A5%E5%AE%9E%E7%8E%B0%E8%B7%AF%E5%BE%84%E5%85%A8%E8%A7%A3%E6%9E%90.md", date: "2026-04-17", summary: "国家已构建公共数据开发利用“1+3”政策体系,明确共享､开放､授权运营三种利用模式｡由于多数公共数据涉及个人隐私､企业商业秘密,无法普遍开放,因此需通过授权运营实现“开发开放”——依托可信数据空间,将数据转化为数据产品,在应用场景中经数据来源者授权后输出服务价值,做到“数据不出域､可用不可见”,这是公共数据价值释放的核心路径｡ 二､公共数据授权运营,究竟授的是什么权? 数据权利涉及主权国家､社会公", quality: 61.5, connections: 0, success_rate: null },
    { id: "td-1", label: "[北京市政数局:北数所已聚拢数据生态企业超1000家]", theme: "可信数据空间", tag_category: "市场", topics: "可信数据空间", source: "data-market-insight", url: "https://cdn.jsdelivr.net/gh/Domi-OpenClaw/file-storage@main/知识管理/km_20260413_000_%E5%8C%97%E4%BA%AC%E5%B8%82%E6%94%BF%E6%95%B0%E5%B1%80%3A%E5%8C%97%E6%95%B0%E6%89%80%E5%B7%B2%E8%81%9A%E6%8B%A2%E6%95%B0%E6%8D%AE%E7%94%9F%E6%80%81%E4%BC%81%E4%B8%9A%E8%B6%85.md", date: "2026-04-13", summary: "2025年,北京市委市政府出台《关于建设数据要素综合试验区 深化数据要素市场化配置改革的实施意见》,明确试验区“243”建设框架,实现从顶层设计到全面建设的良好开局。 具体来看,一方面,北京夯实数据要素基础环境,创新数据产权制度落地路径,出台公共数据资源开发利用、登记管理实施细则等一批数据制度,加快推进北京数据条例立法。鼓励市场主体围绕新材料、消费、药品、空天等领域建设一批可信数据空间,14个在京", quality: 79.5, connections: 0, success_rate: null },
    { id: "lx-1", label: "可信数据流通POC测试报告（朗新科技）", theme: "朗新科技", tag_category: "数据基础设施", topics: "朗新科技", source: "可信数据流通POC测试报告-1.docx", url: "https://github.com/Domi-OpenClaw/file-storage/blob/main/%E6%8A%A5%E5%91%8A/%E5%8F%AF%E4%BF%A1%E6%95%B0%E6%8D%AE%E6%B5%81%E9%80%9APOC%E6%B5%8B%E8%AF%95%E6%8A%A5%E5%91%8A-1.docx", date: "2025-07-01", summary: "朗新科技可信数据流通平台POC测试报告，2025年7-12月测试，覆盖数据接入/流通交易/存证审计/运营管理/安全合规5大模块，328个bug全部修复，测试用例100%通过。支持麒麟OS/瀚高DB/海光CPU国产化替代。性能P99<200ms（100并发）。", quality: 62.9, connections: 0, success_rate: null },
  ]
};

const THEME_CONFIG = {
  "数据基础设施": { "color": "#8B5CF6", "emoji": "🏛️" },
  "可信数据空间": { "color": "#10B981", "emoji": "🔐" },
  "充电桩": { "color": "#F97316", "emoji": "⚡" },
  "虚拟电厂": { "color": "#EF4444", "emoji": "🔋" },
  "朗新科技": { "color": "#3B82F6", "emoji": "🏢" }
};

const TAG_CONFIG = {
  "数据基础设施": { "color": "#8B5CF6", "emoji": "🏛️" },
  "政策": { "color": "#3B82F6", "emoji": "📋" },
  "市场": { "color": "#10B981", "emoji": "📈" },
  "政府": { "color": "#EF4444", "emoji": "🏛️" },
  "金融": { "color": "#F59E0B", "emoji": "💰" },
  "招标": { "color": "#EC4899", "emoji": "📢" },
  "能源": { "color": "#F97316", "emoji": "⚡" }
};
