// Generated by sync-generator.py @ 2026-04-12 03:19
const KNOWLEDGE_DATA = {
  nodes: [
    {
      id: "td-1",
      label: "南方能源行业可信数据空间 — 全套操作指引（13份）",
      category: "可信数据空间",
      summary: "**背景**：南方电网建设的能源行业可信数据空间（data.csg.cn），用于数据产品流通、交易与订阅交付。以下为完整操作手册归档。",
      source: "knowledge-index.md",
      url: "",
      connections: 0
    },
    {
      id: "ndi-1",
      label: "国家数据基础设施技术文件 — NDI-TR系列核心标准（2025年2月发布，试运行6个月）",
      category: "数据基础设施",
      summary: "**背景**：国家数据局2025年2月28日发布，试用期6个月（试行V1.0），后续推动形成数据领域国家标准。构成国家数据基础设施标准体系核心。",
      source: "knowledge-index.md",
      url: "",
      connections: 0
    }
  ],
  links: [
    // links maintained manually
  ]
};

const CATEGORY_CONFIG = {
  "朗新科技":     { "color": "#3B82F6", "emoji": "🏢" },
  "可信数据空间": { "color": "#10B981", "emoji": "🔐" },
  "充电桩":       { "color": "#F97316", "emoji": "⚡" },
  "虚拟电厂":     { "color": "#EF4444", "emoji": "⚡" },
  "数据基础设施": { "color": "#8B5CF6", "emoji": "🏛️" }
};

