#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
知识图谱 data.js 生成器 v6
从 TinyDB（JSON数据库）读取知识节点 → data.js
按 tag 分类：政策/市场/政府/金融/招标/能源/数据基础设施
"""

import sys
import datetime

# TinyDB via skill-image-gen venv
sys.path.insert(0, "/home/admin/.openclaw/skills/skill-image-gen/venv/lib/python3.11/site-packages")
from tinydb import TinyDB

DB_PATH  = "/home/admin/.openclaw/workspace/knowledge/db/knowledge-index.json"
DATA_DIR = "/home/admin/.openclaw/workspace/code-space/knowledge-graph"
DATA_FILE = f"{DATA_DIR}/data.js"

# 分类配置（按 tag 体系）
CC = {
    "数据基础设施": { "color": "#8B5CF6", "emoji": "🏛️" },
    "政策":         { "color": "#3B82F6", "emoji": "📋" },
    "市场":         { "color": "#10B981", "emoji": "📈" },
    "政府":         { "color": "#EF4444", "emoji": "🏛️" },
    "金融":         { "color": "#F59E0B", "emoji": "💰" },
    "招标":         { "color": "#EC4899", "emoji": "📢" },
    "能源":         { "color": "#F97316", "emoji": "⚡" },
    "default":      { "color": "#6B7280", "emoji": "📄" }
}

prefix_map = {
    "数据基础设施": "ndi",
    "政策":        "pol",
    "市场":        "mkt",
    "政府":        "gov",
    "金融":        "fin",
    "招标":        "bid",
    "能源":        "ene",
}

def get_category(record):
    """从 tags 字段推导分类（英文tag→中文分类）"""
    tags_str = record.get("tags", "") or ""
    tag_map = {
        "policy":  "政策",
        "market":  "市场",
        "gov":     "政府",
        "finance": "金融",
        "bidding": "招标",
        "energy":  "能源",
    }
    for tag in tags_str.split(","):
        tag = tag.strip().lower()
        if tag in tag_map:
            return tag_map[tag]
    return "数据基础设施"

# ── 从 TinyDB 读取全部条目 ─────────────────────────────────────────────
db   = TinyDB(DB_PATH)
tbl  = db.table("knowledge")
all_records = tbl.all()
db.close()

# 分类计数器
from collections import OrderedDict
cat_counter = OrderedDict()

nodes_out = []
for r in all_records:
    cat = get_category(r)

    summary = r.get("summary", "") or ""
    if len(summary) < 5:
        continue

    # 稳定ID
    if cat not in cat_counter:
        cat_counter[cat] = 0
    cat_counter[cat] += 1
    prefix = prefix_map.get(cat, "xx")
    nid = f"{prefix}-{cat_counter[cat]}"

    url = r.get("archive_url") or ""
    sr = r.get("success_rate")
    sr_str = "null" if sr is None else str(sr)

    nodes_out.append({
        "id":           nid,
        "label":        r.get("title", ""),
        "category":     cat,
        "summary":      summary[:180].replace('"', "'"),
        "source":       r.get("source", ""),
        "source_date":  r.get("source_date", ""),
        "url":          url,
        "date":         r.get("source_date", ""),
        "quality":      r.get("quality", 0),
        "success_rate": sr,
    })

# 按日期倒序
nodes_out.sort(key=lambda x: x.get("date", ""), reverse=True)

# ── 生成 data.js ──────────────────────────────────────────────────────
ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

nodes_lines = []
for n in nodes_out:
    sr = "null" if n["success_rate"] is None else n["success_rate"]
    nodes_lines.append(
        '    {{ id: "{id}", label: "{label}", category: "{cat}", source: "{src}", '
        'url: "{url}", date: "{date}", connections: 0, success_rate: {sr} }},'.format(
            id=n["id"],
            label=n["label"].replace('"', '\\"'),
            cat=n["category"],
            src=n["source"],
            url=n["url"],
            date=n["date"],
            sr=sr
        )
    )

links_lines = []  # 暂不实现关联关系

cc_lines = []
for name, cfg in CC.items():
    if name != "default":
        cc_lines.append(f'  "{name}": {{ "color": "{cfg["color"]}", "emoji": "{cfg["emoji"]}" }}')

data_js = f"""// Generated by sync-generator.py v6 @ {ts}
// Source: TinyDB
const KNOWLEDGE_DATA = {{
  nodes: [
{chr(10).join(nodes_lines)}
  ],
  links: [
{chr(10).join(links_lines)}
  ]
}};

const CATEGORY_CONFIG = {{
{','.join(cc_lines)}
}};
"""

# summaries.js
summaries_js = "const SUMMARIES = {\n"
for n in nodes_out:
    s = n["summary"].replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    summaries_js += f'  "{n["id"]}": "{s}",\n'
summaries_js += "};\n"

with open(DATA_FILE, "w", encoding="utf-8") as f:
    f.write(data_js)

summary_file = f"{DATA_DIR}/summaries.js"
with open(summary_file, "w", encoding="utf-8") as f:
    f.write(summaries_js)

# 分类统计
from collections import Counter
cat_counts = Counter(n["category"] for n in nodes_out)
print(f"✅ 生成完成")
print(f"   总节点: {len(nodes_out)}")
for cat, cnt in sorted(cat_counts.items(), key=lambda x: -x[1]):
    print(f"   {cat}: {cnt}")
print(f"   data.js: {len(data_js)} bytes")
