#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
知识图谱 data.js 生成器 v5
从 TinyDB（JSON数据库）读取知识节点 → data.js
不再解析 markdown，数据库是唯一数据源
"""

import sys
import datetime

# TinyDB via skill-image-gen venv
sys.path.insert(0, "/home/admin/.openclaw/skills/skill-image-gen/venv/lib/python3.11/site-packages")
from tinydb import TinyDB, Query

DB_PATH  = "/home/admin/.openclaw/workspace/knowledge/db/knowledge-index.json"
DATA_DIR = "/home/admin/.openclaw/workspace/code-space/knowledge-graph"
DATA_FILE = f"{DATA_DIR}/data.js"

# 分类配置
CC = {
    "朗新科技":     { "color": "#3B82F6", "emoji": "🏢" },
    "可信数据空间": { "color": "#10B981", "emoji": "🔐" },
    "充电桩":       { "color": "#F97316", "emoji": "⚡" },
    "虚拟电厂":     { "color": "#EF4444", "emoji": "🔋" },
    "数据基础设施": { "color": "#8B5CF6", "emoji": "🏛️" },
    "default":      { "color": "#6B7280", "emoji": "📄" }
}

# ── 从 TinyDB 读取全部条目 ─────────────────────────────────────────────
db   = TinyDB(DB_PATH)
tbl  = db.table("knowledge")
all_records = tbl.all()
db.close()

# 分类计数器（保证ID稳定）
from collections import OrderedDict
cat_counter = OrderedDict()
prefix_map  = {"朗新科技":"lx","可信数据空间":"td","充电桩":"cd","虚拟电厂":"vp","数据基础设施":"ndi"}

def get_category(record):
    tags = record.get("tags", "") or ""
    for cat in CC:
        if cat != "default" and cat in tags:
            return cat
    return "数据基础设施"

nodes_out = []
for r in all_records:
    cat = get_category(r)

    # 跳过没有摘要的条目
    summary = r.get("summary", "") or ""
    if len(summary) < 5:
        continue

    # 稳定ID
    if cat not in cat_counter:
        cat_counter[cat] = 0
    cat_counter[cat] += 1
    prefix = prefix_map.get(cat, "xx")
    nid = f"{prefix}-{cat_counter[cat]}"

    # URL
    url = r.get("archive_url") or ""

    # success_rate
    sr = r.get("success_rate")
    sr_str = "null" if sr is None else str(sr)

    nodes_out.append({
        "id":           nid,
        "label":        r.get("title", ""),
        "category":     cat,
        "summary":      summary[:180].replace('"', "'"),
        "source":       r.get("source", ""),
        "source_date":  r.get("source_date", ""),
        "url":          url,
        "date":         r.get("source_date", ""),   # 复用source_date作为date
        "quality":      r.get("quality", 0),
        "success_rate": sr,
    })

# 按日期倒序
nodes_out.sort(key=lambda x: x.get("date", ""), reverse=True)

# ── 生成 data.js ──────────────────────────────────────────────────────
ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

nodes_lines = []
for n in nodes_out:
    sr = "null" if n["success_rate"] is None else n["success_rate"]
    nodes_lines.append(
        '    {{ id: "{id}", label: "{label}", category: "{cat}", source: "{src}", '
        'url: "{url}", date: "{date}", connections: 0, success_rate: {sr} }}'.format(
            id=n["id"],
            label=n["label"].replace('"', '\\"'),
            cat=n["category"],
            src=n["source"],
            url=n["url"],
            date=n["date"],
            sr=sr
        )
    )

links_lines = []  # 暂不实现关联关系

cc_lines = []
for name, cfg in CC.items():
    if name != "default":
        cc_lines.append(f'  "{name}": {{ "color": "{cfg["color"]}", "emoji": "{cfg["emoji"]}" }}')

data_js = f"""// Generated by sync-generator.py v5 @ {ts}
// Source: TinyDB (不再解析 markdown)
const KNOWLEDGE_DATA = {{
  nodes: [
{chr(10).join(nodes_lines)}
  ],
  links: [
{chr(10).join(links_lines)}
  ]
}};

const CATEGORY_CONFIG = {{
{','.join(cc_lines)}
}};
"""

# ── 生成 summaries.js（完整摘要 lazy load）────────────────────────────────
summaries_js = "const SUMMARIES = {\n"
for n in nodes_out:
    s = n["summary"].replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    summaries_js += f'  "{n["id"]}": "{s}",\n'
summaries_js += "};\n"

with open(DATA_FILE, "w", encoding="utf-8") as f:
    f.write(data_js)

summary_file = f"{DATA_DIR}/summaries.js"
with open(summary_file, "w", encoding="utf-8") as f:
    f.write(summaries_js)

print(f"✅ 生成完成")
print(f"   节点数: {len(nodes_out)}")
print(f"   data.js: {len(data_js)} bytes")
print(f"   summaries.js: {len(summaries_js)} bytes")
